/*
 * File: MyWindow.ui.js
 * Date: Sat Mar 19 2011 16:49:26 GMT-0600 (Hora estándar central (México))
 * 
 * This file was generated by Ext Designer version 1.1.1.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

MyWindowUi = Ext.extend(Ext.Window, {
    title: 'Inicio de sesion',
    width: 379,
    height: 181,
    tpl: '',
    hideBorders: true,
    layout: 'absolute',
    closable: false,
    initComponent: function() {
        this.items = [
            {
                xtype: 'form',
                height: 133,
                labelPad: 6,
                hideParent: true,
                hideBorders: true,
                border: false,
                frame: true,
                standardSubmit: true,
                method: 'POST',
                items: [
                    {
                        xtype: 'textfield',
                        anchor: '100%',
                        fieldLabel: 'Nombre',
                        height: 30
                    },
                    {
                        xtype: 'textfield',
                        fieldLabel: 'Contraseña',
                        anchor: '100%',
                        inputType: 'password',
                        invalidText: 'Contraseña invalida',
                        height: 30
                    },
                    {
                        xtype: 'button',
                        text: 'Iniciar',
                        width: 90,
                        autoScroll: true,
                        type: 'submit',
                        stateful: true,
				   handler: function(){
					alert(this.id);
			    },	
                        id: 'Iniciar'
                    },
                    {
                        xtype: 'button',
                        text: 'Reiniciar',
                        width: 90,
                        autoScroll: true,
                        type: 'reset'
                    }
                ]
            }
        ];
        MyWindowUi.superclass.initComponent.call(this);
    }
});
