/*
 * File: xds_index.js
 * Date: Sat Mar 19 2011 16:49:26 GMT-0600 (Hora estándar central (México))
 * 
 * This file was generated by Ext Designer version 1.1.1.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.onReady(function() {
    Ext.QuickTips.init();
    var cmp1 = new MyWindow({
        renderTo: Ext.getBody()
    });
    cmp1.show();
});
