/*
 * File: MyButton.ui.js
 * Date: Sat Mar 19 2011 16:43:11 GMT-0600 (Hora estándar central (México))
 * 
 * This file was generated by Ext Designer version 1.1.1.
 * http://www.sencha.com/products/designer/
 *
 * This file was manually exported.
 */

MyButtonUi = Ext.extend(Ext.Button, {
    text: 'Iniciar',
    width: 90,
    autoScroll: true,
    type: 'submit',
    stateful: true,
    id: 'Iniciar',
    initComponent: function() {
        MyButtonUi.superclass.initComponent.call(this);
    }
});
