/*
 * File: MyForm.ui.js
 * Date: Sat Mar 19 2011 15:50:02 GMT-0600 (Hora estándar central (México))
 * 
 * This file was generated by Ext Designer version 1.1.1.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

MyFormUi = Ext.extend(Ext.form.FormPanel, {
    height: 140,
    labelPad: 6,
    hideParent: true,
    hideBorders: true,
    border: false,
    frame: true,
    initComponent: function() {
        this.items = [
            {
                xtype: 'textfield',
                anchor: '100%',
                fieldLabel: 'Nombre',
                height: 30
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Contraseña',
                anchor: '100%',
                inputType: 'password',
                invalidText: 'Contraseña invalida',
                height: 30
            },
            {
                xtype: 'container',
                height: 61,
                layout: 'absolute',
                items: [
                    {
                        xtype: 'container',
                        layout: 'column',
                        autoScroll: true,
                        height: 41,
                        activeItem: 0,
                        width: 200,
                        x: 150,
                        y: 10,
                        items: [
                            {
                                xtype: 'button',
                                text: 'Iniciar',
                                width: 100,
                                autoScroll: true,
                                type: 'submit',
                                stateful: true,
                                stateEvents: 'prueba.html',
                                id: 'Iniciar'
                            },
                            {
                                xtype: 'button',
                                text: 'Reiniciar',
                                width: 90,
                                autoScroll: true,
                                type: 'reset',
                                region: 'center'
                            }
                        ]
                    }
                ]
            }
        ];
        MyFormUi.superclass.initComponent.call(this);
    }
});
