/*
 * File: MyForm.js
 * Date: Sat Mar 19 2011 15:49:57 GMT-0600 (Hora estándar central (México))
 * 
 * This file was generated by Ext Designer version 1.1.1.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

MyForm = Ext.extend(MyFormUi, {
    initComponent: function() {
        MyForm.superclass.initComponent.call(this);
    }
});
Ext.reg('myform', MyForm);