/*
 * File: MyWindow.ui.js
 * Date: Sat Mar 19 2011 15:50:02 GMT-0600 (Hora estándar central (México))
 * 
 * This file was generated by Ext Designer version 1.1.1.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

MyWindowUi = Ext.extend(Ext.Window, {
    title: 'Inicio de sesion',
    width: 379,
    height: 181,
    tpl: '',
    hideBorders: true,
    layout: 'absolute',
    closable: false,
    initComponent: function() {
        this.items = [
            {
                x: 0,
                y: 0,
                xtype: 'myform'
            }
        ];
        MyWindowUi.superclass.initComponent.call(this);
    }
});
